# Generated by Django 5.0.4 on 2024-04-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum42', '0002_remove_user_date_joined_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
